### ISSUE TITLE
difficulty with downloading live

### ISSUE THREAD

**Issue by hairygodfather** [adwisatya/TwitterSpaces2Text#2]
Hello,

So I've tried jumping into a live twitter space that has already started.
Let's say I would like to grab the transcript from the beginning to capture what I have missed.
So I go ahead and grab the spaces id and insert it.
The script does capture from the start of the stream through the timestamp that the script was initialized.
The script works for both 'recorded by host' and 'non-recorded by host' streams.
It completes the output as desired.
As you would expect, there is an error generated eventually since the spaces has not ended yet as follows:

[start]
C:\path>py twitspace07-10-21.py >> test301a.txt
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\path\twitspace07-10-21.py", line 4, in <module>
    extractor.getCaption("1ZkJzbbELoaJv")
  File "C:\Python\lib\site-packages\TwitterSpaces2Text\Extractor.py", line 50, in getCaption
    raw_data = self.getCurrentCaption(cursor)
  File "C:\Python\lib\site-packages\TwitterSpaces2Text\Extractor.py", line 40, in getCurrentCaption
    json={"access_token":self.access_token      ,"cursor":cursor,"limit":1000,"since":None,"quick_get":True}).json()
  File "C:\Python\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[end]

So, I think, no problem, i'll just delete the initial output text file and rerun the script a few minutes later to capture a longer transcript.

However, the problems start if I try to *rerun* the same script for the same space id subsequently. 
The intent is to replace the already downloaded transcript by extending the transcript timeframe beyond the initially downloaded timeframe.
What happens is that the output will keep ending at the same initial timestamped request point (despite the fact that the script is being initialized with a much later timestamp while the space is still live, or for a recorded stream rerunning after the stream has ended)

1) I have tried closing the command line window and reopening it.
2) I have tried clearing the cache with "cleanpy -avf --exclude-envs c:\python"
3) it seems like the initially downloaded output is cached somewhere but I can't find out where it is so I can flush it.
4) the issue persists even if the stream is recorded and I wait until after the stream ends before rerunning the script.
5) I have also tried renaming the py file and renaming the output text file name before rerunning the script. I have tried placing the py file in a different folder.
6) so the cache seems to be tied directly to the specific spaces id.
7) my setup - windows 10, Python 3.10.5, pip 22.1.2
8) the problem persists regardless of the output file - for example i have tried removing the write to file aspect and the screen output also stops at the same initial timestamp download point.

Thanks in advance.

**Comment by oszilloskop** [comment]
I got the same issue with a Debian VM and Python 3.9.2

The error message looks like following:
```
Traceback (most recent call last):
  File "/root/TwitterSpaces2Text", line 3, in <module>
    extractor.getCaption("1MYGNngaVLbGw")
  File "/usr/local/lib/python3.9/dist-packages/TwitterSpaces2Text/Extractor.py", line 50, in getCaption
    raw_data = self.getCurrentCaption(cursor)
  File "/usr/local/lib/python3.9/dist-packages/TwitterSpaces2Text/Extractor.py", line 39, in getCurrentCaption
    return requests.post('https://chatman-replay-eu-central-1.pscp.tv/chatapi/v1/history',
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
A fast internet search shows me that is a JSON-Parser error.

**Comment by oszilloskop** [comment]
I got the same issue with a Debian VM and Python 3.9.2
The error message looks like following:
```
Traceback (most recent call last):
  File "/root/TwitterSpaces2Text", line 3, in <module>
    extractor.getCaption("1Mxxxxxxxxxxxxxxxx")
  File "/usr/local/lib/python3.9/dist-packages/TwitterSpaces2Text/Extractor.py", line 50, in getCaption
    raw_data = self.getCurrentCaption(cursor)
  File "/usr/local/lib/python3.9/dist-packages/TwitterSpaces2Text/Extractor.py", line 39, in getCurrentCaption
    return requests.post('https://chatman-replay-eu-central-1.pscp.tv/chatapi/v1/history',
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
A fast internet search shows me that it is a JSON content syntax error.

**Comment by adwisatya** [comment]
Hi, this library is not designed to download live Twitter Spaces transcript so that is expected/

**Comment by oszilloskop** [comment]
@hairygodfather please have a look in following PR: https://github.com/adwisatya/TwitterSpaces2Text/pull/4

**Comment by hairygodfather** [comment]
@oszilloskop   ... thank you. your code changes overcome the live issue. appreciate it!
